### ISSUE TITLE
Is there some way to send a photo without a path, with the photo content directly?

### ISSUE THREAD

**Issue by jhg** [rockneurotiko/ex_gram#55]

**Comment by rockneurotiko** [comment]
:wave: 

It's not possible with the current release, but I created a branch with the feature. I tried myself, but I would appreciate you can try it before releasing it.

You just need to set the version in your `mix.exs` to: 
`{:ex_gram, github: "rockneurotiko/ex_gram", branch: "send_file_contents"}`

And where you want to send the file contents, instead of `{:file, "path"}`, you use `{:file_content, "CONTENTS", "filename.ext"}`, ex:

``` elixir
ExGram.send_document(111111111, {:file_content, "abcde", "myfile.txt"}, bot: :bot)
```

**Comment by rockneurotiko** [comment]
I merged the branch, you can use the version `"~> 0.21"` in order to have the `file_content` feature

**Comment by jhg** [comment]
![IMG_20201230_234457](https://user-images.githubusercontent.com/1288711/103385063-3b788b80-4af9-11eb-9e5f-7fe746a4bd03.jpg)
Thanks @rockneurotiko 🤗 it works well! I'm sorry late to try it. I continue the bot today and now it can send the photo downloaded from this person does not exist directly without tmp file.
